version: 2
updates:
  # Maintain dependencies for Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "github.com/gomodule/redigo"
        # For github.com/gomodule/redigo, ignore version v2.0.0
        versions: ["v2.0.0"]
  - package-ecosystem: "gomod"
    directory: "/snap/local/hooks"
    schedule:
      interval: "daily"
