run:
  timeout: 5m
linters:
  disable:
  enable:
    - gosec
linters-settings:
  gosec:
    excludes:
      # G115: integer overflow conversion
      # exclude the rule since it tends to be false positive
      - G115
