FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine as builder

RUN apk add --no-cache python3 py3-pip bash

RUN git clone https://github.com/microsoft/restler-fuzzer.git

RUN cd restler-fuzzer; mkdir -p restler_bin
WORKDIR /restler-fuzzer
RUN python3 ./build-restler.py --dest_dir ./restler_bin/

COPY fuzzing_docker.sh /restler-fuzzer/fuzzing.sh
COPY /openapi/v3/core-data.yaml /restler-fuzzer/

ENTRYPOINT ["/restler-fuzzer/fuzzing.sh"]
CMD ["core-data", "/restler-fuzzer", "core-data.yaml"]