[Service]
Host = "localhost"
Port = 49982
ConnectRetries = 3
Labels = []
OpenMsg = "device mqtt started"
MaxResultCount = 50000
Timeout = 5000
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Host = "localhost"
Port = 8500
CheckInterval = "10s"
FailLimit = 3
FailWaitTime = 10

[Clients]
  [Clients.Data]
  Name = "edgex-core-data"
  Protocol = "http"
  Host = "localhost"
  Port = 48080
  Timeout = 50000

  [Clients.Metadata]
  Name = "edgex-core-metadata"
  Protocol = "http"
  Host = "localhost"
  Port = 48081
  Timeout = 50000

  [Clients.Logging]
  Name = "edgex-support-logging"
  Protocol = "http"
  Host = "localhost"
  Port = 48061

[Device]
  DataTransform = true
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = "./res/example"

[Logging]
EnableRemote = false
File = "./device-mqtt.log"
Level = "DEBUG"

# Pre-define Devices
[[DeviceList]]
  Name = "MQTT test device"
  Profile = "Test.Device.MQTT.Profile"
  Description = "MQTT device is created for test purpose"
  Labels = [ "MQTT", "test"]
  [DeviceList.Addressable]
    name = "Gateway address"
    Protocol = "TCP"
    Address = "0.0.0.0"
    Port = 1883
    Publisher = "CommandPublisher"
    user = "admin"
    password = "public"
    topic = "CommandTopic"

# Pre-define Schedule Configuration
[[Schedules]]
Name = "mqtt-30sec-schedule"
Frequency = "PT30S"

[[ScheduleEvents]]
Name = "readRandnum"
Schedule = "mqtt-30sec-schedule"
  [ScheduleEvents.Addressable]
  HTTPMethod = "GET"
Path = "/api/v1/device/name/MQTT test device/testrandnum"
