// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	errors "github.com/edgexfoundry/go-mod-core-contracts/v3/errors"
	mock "github.com/stretchr/testify/mock"

	models "github.com/edgexfoundry/go-mod-core-contracts/v3/models"
)

// Sender is an autogenerated mock type for the Sender type
type Sender struct {
	mock.Mock
}

// Send provides a mock function with given fields: notification, address
func (_m *Sender) Send(notification models.Notification, address models.Address) (string, errors.EdgeX) {
	ret := _m.Called(notification, address)

	var r0 string
	if rf, ok := ret.Get(0).(func(models.Notification, models.Address) string); ok {
		r0 = rf(notification, address)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 errors.EdgeX
	if rf, ok := ret.Get(1).(func(models.Notification, models.Address) errors.EdgeX); ok {
		r1 = rf(notification, address)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.EdgeX)
		}
	}

	return r0, r1
}

type mockConstructorTestingTNewSender interface {
	mock.TestingT
	Cleanup(func())
}

// NewSender creates a new instance of Sender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSender(t mockConstructorTestingTNewSender) *Sender {
	mock := &Sender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
