#
# Copyright (c) 2017-2018
# Mainflux
# Cavium
#
# SPDX-License-Identifier: Apache-2.0
#

FROM golang:1.9-alpine AS builder
RUN apk --update add \
    make \
    git \
    glide \
    zeromq-dev \
    build-base
WORKDIR $GOPATH/src/github.com/edgexfoundry/edgex-go
COPY . .
RUN glide install
RUN make cmd/export-client/export-client

FROM scratch
COPY --from=builder /go/src/github.com/edgexfoundry/edgex-go/cmd/export-client/export-client /
ENTRYPOINT ["/export-client"]
