#
# Copyright (c) 2017 Mainflux
#
# SPDX-License-Identifier: Apache-2.0
#

FROM golang:1.9-alpine AS builder
WORKDIR /go/src/github.com/edgexfoundry/edgex-go
RUN apk update && apk add make
COPY . .
RUN make cmd/export-client/export-client

FROM scratch
COPY --from=builder /go/src/github.com/edgexfoundry/edgex-go/cmd/export-client/export-client /
ENTRYPOINT ["/export-client"]
