#
# Copyright (c) 2017-2018
# Mainflux
# Cavium
#
# SPDX-License-Identifier: Apache-2.0
#

FROM golang:1.9-alpine AS builder
WORKDIR /go/src/github.com/tsconn23/edgex-go
RUN apk update && apk add make
COPY . .
RUN make cmd/export-distro/export-distro

FROM alpine:3.7
COPY --from=builder /go/src/github.com/tsconn23/edgex-go/cmd/export-distro/export-distro /
ENTRYPOINT ["/export-distro"]
