#
# Copyright (c) 2018
# Cavium
#
# SPDX-License-Identifier: Apache-2.0
#

FROM golang:1.9-alpine AS builder
WORKDIR /go/src/github.com/tsconn23/edgex-go
RUN apk update && apk add make
COPY . .
RUN make cmd/support-logging/support-logging

FROM scratch
COPY --from=builder /go/src/github.com/tsconn23/edgex-go/cmd/support-logging/support-logging /
ENTRYPOINT ["/support-logging"]
