#
# Copyright (c) 2017 Mainflux
#
# SPDX-License-Identifier: Apache-2.0
#

FROM golang:1.8-alpine AS builder
WORKDIR /go/src/github.com/drasko/edgex-export
COPY . .
RUN cd cmd/distro && CGO_ENABLED=0 GOOS=linux go build -ldflags "-s" -a -installsuffix cgo -o exe

FROM scratch
COPY --from=builder /go/src/github.com/drasko/edgex-export/cmd/distro/exe /
ENTRYPOINT ["/exe"]
