[SecretService]
Scheme = "https"
Server = "localhost"
ServerName = "edgex-vault"
Port = 8200
CaFilePath = '/tmp/edgex/secrets/ca/ca.pem'

[TokenFileProvider]
PrivilegedTokenPath = "resp-init.json"
ConfigFile = "res/token-config.json"
OutputDir = "/tmp"
OutputFilename = "secrets-token.json"

[Writable]
LogLevel = 'DEBUG'

[Logging]
EnableRemote = false
File = './logs/security-file-token-provider.log'
