# This TOML manifest file specifies the services managed by the SMA.
# The bootstrap property (like –manifest) will indicate to the SMA to get this TOML configuration from the file system.
# The SMA needs the details provided in this TOML to stop/start/restart each service that the SMA manages.
# What about specifying the edgexsecurity service to use?
# Different versions of this manifest may exist depending on how/where EdgeX is deployed (Docker v. Snappy, Windows v. Linux, etc.).
# In the first release of the SMA, the manifest will be static.
# In the future, the manifest may be more dynamic or even provided by some 3rd party orchestrator.

# title = 'EdgeX manifest for consumption by the SMA to bootstrap managed services.'

# edgex-support-notifications
EdgexServicesNotificationsName = 'notifications'
EdgexServicesNotificationsHost = 'localhost'
EdgexServicesNotificationsPort = 48060
EdgexServicesNotificationsProtocol = 'http'
EdgexServicesNotificationsCommandstop = 'stop'
EdgexServicesNotificationsCommandstart = 'start'

OperationsType = 'docker'
# OperationsType = 'os'
