// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import models "github.com/edgexfoundry/go-mod-core-contracts/models"

// Loader is an autogenerated mock type for the Loader type
type Loader struct {
	mock.Mock
}

// ReadingsByValueDescriptor provides a mock function with given fields: name, limit
func (_m *Loader) ReadingsByValueDescriptor(name string, limit int) ([]models.Reading, error) {
	ret := _m.Called(name, limit)

	var r0 []models.Reading
	if rf, ok := ret.Get(0).(func(string, int) []models.Reading); ok {
		r0 = rf(name, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Reading)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = rf(name, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
