ConsulProfilesActive = 'docker;go'
ReadLimit = 100
ServerPort =
ServiceAddress = 'localhost'
ServicePort = 48081
ConsulPort = 8500
ServiceTimeout = 5000
ConsulHost = 'localhost'
ConsulCheckAddress = 'http://localhost:48085/api/v1/ping'
CheckInterval = '10s'

AppOpenMsg = 'This is the Core Scheduler Micro Service'
EnableRemoteLogging = false
LoggingFile = './logs/edgex-core-suppor-scheduler.log'
LoggingRemoteUrl = 'http://localhost:48061/api/v1/logs'
ServiceLabels = ''
ServiceCallback = '/v1/callbacks'
ServiceConnectRetries = 6
ServiceConnectInterval = 10000
ScheduleInterval = 500
DefaultScheduleName = 'midnight'
DefaultScheduleFrequency = 'P1D'
DefaultScheduleStart = '20180101T000000'
DefaultScheduleEventName = 'scrub-pushed-events,scrube-aged-events'
DefaultScheduleEventMethod = 'DELETE,DELETE'
DefaultScheduleEventService = 'core-data,core-data'
DefaultScheduleEventParameters = ''
DefaultScheduleEventPath = '/api/v1/event/scrub,/api/v1/event/removeold/age/604800000'
DefaultScheduleEventSchedule = 'midnight,midnight'
DefaultScheduleEventScheduler = 'support-scheduler,support-scheduler'
MetaAddressableURL = 'http://localhost:48081/api/v1/addressable'
MetaDeviceServiceURL = 'http://localhost:48081/api/v1/deviceservice'
MetaDeviceProfileURL = 'http://localhost:48081/api/v1/deviceprofile'
MetaDeviceURL = 'http://localhost:48081/api/v1/device'
MetaDeviceReportURL = 'http://localhost:48081/api/v1/devicereport'
MetaCommandURL = 'http://localhost:48081/api/v1/command'
MetaEventURL = 'http://localhost:48081/api/v1/scheduleevent'
MetaScheduleURL = 'http://localhost:48081/api/v1/schedule'
MetaProvisionWatcherURL = 'http://localhost:48081/api/v1/provisionwatcher'

