// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import agent "github.com/edgexfoundry/edgex-go/internal/system/agent"
import mock "github.com/stretchr/testify/mock"

// MSMClient is an autogenerated mock type for the MSMClient type
type MSMClient struct {
	mock.Mock
}

// ProcessConfigResponse provides a mock function with given fields: response
func (_m *MSMClient) ProcessConfigResponse(response string) agent.ConfigRespMap {
	ret := _m.Called(response)

	var r0 agent.ConfigRespMap
	if rf, ok := ret.Get(0).(func(string) agent.ConfigRespMap); ok {
		r0 = rf(response)
	} else {
		r0 = ret.Get(0).(agent.ConfigRespMap)
	}

	return r0
}

// ProcessMetricsResponse provides a mock function with given fields: response
func (_m *MSMClient) ProcessMetricsResponse(response string) agent.MetricsRespMap {
	ret := _m.Called(response)

	var r0 agent.MetricsRespMap
	if rf, ok := ret.Get(0).(func(string) agent.MetricsRespMap); ok {
		r0 = rf(response)
	} else {
		r0 = ret.Get(0).(agent.MetricsRespMap)
	}

	return r0
}
