[Writable]
LogLevel = "DEBUG"

[Service]
Port = 59841
StartupMsg = "This is the SPIFFE token provider microservice"

[TokenConfig]
#PrivilegedTokenPath = "UNUSED"
#ConfigFile = "UNUSED"
#OutputDir = "UNUSED"
#OutputFilename = "UNUSED"
DefaultTokenTTL = "1h"
DefaultJWTTTL = "15m"
UserPassMountPoint = "userpass"

[SPIFFE]
EndpointSocket = "/tmp/edgex/secrets/spiffe/public/api.sock"
TrustDomain = "edgexfoundry.org"
