Writable:
  LogLevel: INFO
  InsecureSecrets:
    mqtt:
      SecretName: mqtt
      SecretData:
        username: ""
        password: ""
        cacert: ""
        clientcert: ""
        clientkey: ""

Service:
  Host: localhost
  Port: 59890
  StartupMsg: "This is the Core Keeper Microservice"
  HealthCheckInterval: "10s"
  ServerBindAddr: "" # Leave blank so default to Host value unless different value is needed.
  MaxResultCount: 1024
  MaxRequestSize: 0 # Not currently used. Defines the maximum size of http request body in bytes
  RequestTimeout: "5s"
  EnableNameFieldEscape: false # The name field escape could allow the system to use special or Chinese characters in the different name fields, including device, profile, and so on.  If the EnableNameFieldEscape is false, some special characters might cause system error.  TODO: This is set to false by default to avoid breaking change and will be removed in EdgeX 4.0
  CORSConfiguration:
    EnableCORS: false
    CORSAllowCredentials: false
    CORSAllowedOrigin: "https://localhost"
    CORSAllowedMethods: "GET, POST, PUT, PATCH, DELETE"
    CORSAllowedHeaders: "Authorization, Accept, Accept-Language, Content-Language, Content-Type, X-Correlation-ID"
    CORSExposeHeaders: "Cache-Control, Content-Language, Content-Length, Content-Type, Expires, Last-Modified, Pragma, X-Correlation-ID"
    CORSMaxAge: 3600

MessageBus:
  BaseTopicPrefix: "edgex/configs" # /<key> will be added to this Base Topic prefix
  Optional:
    # Default MQTT Specific options that need to be here to enable environment variable overrides of them
    Qos:  "0" # Quality of Service values are 0 (At most once), 1 (At least once) or 2 (Exactly once)
    KeepAlive: "10" # Seconds (must be 2 or greater)
    Retained: "false"
    AutoReconnect: "true"
    ConnectTimeout: "5" # Seconds
    SkipCertVerify: "false"
    # Additional Default NATS Specific options that need to be here to enable environment variable overrides of them
    Format: "nats"
    RetryOnFailedConnect: "true"
    QueueGroup: ""
    Durable: ""
    AutoProvision: "true"
    Deliver: "new"
    DefaultPubRetryAttempts: "2"
    Subject: "edgex/#" # Required for NATS JetStream only for stream auto-provisioning
    ClientId: "core-keeper"
