// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import models "github.com/edgexfoundry/go-mod-core-contracts/models"

// NotificationWriter is an autogenerated mock type for the NotificationWriter type
type NotificationWriter struct {
	mock.Mock
}

// AddNotification provides a mock function with given fields: n
func (_m *NotificationWriter) AddNotification(n models.Notification) (string, error) {
	ret := _m.Called(n)

	var r0 string
	if rf, ok := ret.Get(0).(func(models.Notification) string); ok {
		r0 = rf(n)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(models.Notification) error); ok {
		r1 = rf(n)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
