// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	mqtt "github.com/eclipse/paho.mqtt.golang"
	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// AddRoute provides a mock function with given fields: topic, callback
func (_m *Client) AddRoute(topic string, callback mqtt.MessageHandler) {
	_m.Called(topic, callback)
}

// Connect provides a mock function with given fields:
func (_m *Client) Connect() mqtt.Token {
	ret := _m.Called()

	var r0 mqtt.Token
	if rf, ok := ret.Get(0).(func() mqtt.Token); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(mqtt.Token)
		}
	}

	return r0
}

// Disconnect provides a mock function with given fields: quiesce
func (_m *Client) Disconnect(quiesce uint) {
	_m.Called(quiesce)
}

// IsConnected provides a mock function with given fields:
func (_m *Client) IsConnected() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// IsConnectionOpen provides a mock function with given fields:
func (_m *Client) IsConnectionOpen() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// OptionsReader provides a mock function with given fields:
func (_m *Client) OptionsReader() mqtt.ClientOptionsReader {
	ret := _m.Called()

	var r0 mqtt.ClientOptionsReader
	if rf, ok := ret.Get(0).(func() mqtt.ClientOptionsReader); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(mqtt.ClientOptionsReader)
	}

	return r0
}

// Publish provides a mock function with given fields: topic, qos, retained, payload
func (_m *Client) Publish(topic string, qos byte, retained bool, payload interface{}) mqtt.Token {
	ret := _m.Called(topic, qos, retained, payload)

	var r0 mqtt.Token
	if rf, ok := ret.Get(0).(func(string, byte, bool, interface{}) mqtt.Token); ok {
		r0 = rf(topic, qos, retained, payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(mqtt.Token)
		}
	}

	return r0
}

// Subscribe provides a mock function with given fields: topic, qos, callback
func (_m *Client) Subscribe(topic string, qos byte, callback mqtt.MessageHandler) mqtt.Token {
	ret := _m.Called(topic, qos, callback)

	var r0 mqtt.Token
	if rf, ok := ret.Get(0).(func(string, byte, mqtt.MessageHandler) mqtt.Token); ok {
		r0 = rf(topic, qos, callback)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(mqtt.Token)
		}
	}

	return r0
}

// SubscribeMultiple provides a mock function with given fields: filters, callback
func (_m *Client) SubscribeMultiple(filters map[string]byte, callback mqtt.MessageHandler) mqtt.Token {
	ret := _m.Called(filters, callback)

	var r0 mqtt.Token
	if rf, ok := ret.Get(0).(func(map[string]byte, mqtt.MessageHandler) mqtt.Token); ok {
		r0 = rf(filters, callback)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(mqtt.Token)
		}
	}

	return r0
}

// Unsubscribe provides a mock function with given fields: topics
func (_m *Client) Unsubscribe(topics ...string) mqtt.Token {
	_va := make([]interface{}, len(topics))
	for _i := range topics {
		_va[_i] = topics[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 mqtt.Token
	if rf, ok := ret.Get(0).(func(...string) mqtt.Token); ok {
		r0 = rf(topics...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(mqtt.Token)
		}
	}

	return r0
}

type mockConstructorTestingTNewClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewClient(t mockConstructorTestingTNewClient) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
