[Uom]
Source="reference to source for all UoM if not specified below"
  [Uom.Units]
    [Uom.Units.temperature]
    Source="www.weather.com"
    Values=["C","F","K"]
    [Uom.Units.weights]
    Source="www.usa.gov/federal-agencies/weights-and-measures-division"
    Values=["lbs","ounces","kilos","grams"]
