#
# Copyright (c) 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#

LogLevel: DEBUG
SecretStore:
  Type: vault
  Protocol: http
  Host: localhost
  Port: 8200
  CertPath: ""
  CaFilePath: ""
  CertFilePath: ""
  KeyFilePath: ""
  # for root token use: /vault/config/assets
  # for service token use: /tmp/edgex/secrets/security-proxy-setup 
  TokenFolderPath: /vault/config/assets
  # for root token use: resp-init.json
  # for service token use: secrets-token.json
  TokenFile: resp-init.json

# FIXME whittle this down more
