openapi: 3.0.0
info:
  title: system-agent
  version: 1.2.0
servers:
- url: http://localhost:48090/api
paths:
  /v1/config/{services}:
    get:
      description: Fetch the configuration of the specified EdgeX services by their
        unique names.
      parameters:
      - name: services
        in: path
        description: A comma-separated list of EdgeX service names to query for
          configuration.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        200:
          description: A list of configuration data corresponding to each requested,
            valid service.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/config'
        500:
          description: For unknown or unanticipated issues.
  /v1/metrics/{services}:
    get:
      description: Fetch the operating performance metrics of the specified EdgeX
        unique names.
      parameters:
      - name: services
        in: path
        description: A comma-separated list of EdgeX service names to query for
          configuration.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        200:
          description: A list of metrics data corresponding to each requested,
            valid service.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/metric'
        500:
          description: For unknown or unanticipated issues.
  /v1/health/{services}:
    get:
      description: Fetch the health of the specified EdgeX services by their
        unique names.
      parameters:
        - name: services
          in: path
          description: A comma-separated list of EdgeX service names to query for
            health.
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        200:
          description: A list of health data corresponding to each requested,
            valid service.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/health'
        500:
          description: For unknown or unanticipated issues.
  /v1/operation:
    post:
      description: Issue a start, stop or restart action to the specified services.  HTTP
        500 for unknown or unanticipated issues.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/operation'
        required: true
      responses:
        200:
          description: A list of services and their executors.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/operation'
        500:
          description: For unknown or unanticipated issues.
  /v1/ping:
    get:
      description: Test service providing an indication that the service is available.
      responses:
        200:
          description: Return value of "pong"
        503:
          description: For unknown or unanticipated issues
  /version:
    get:
      description: Get the API version
      responses:
        200:
          description: The service's API version as JSON document
components:
  schemas:
    config:
      title: config
      type: object
      properties:
        Config:
          title: Config
          type: string
        Service:
          title: Service
          type: string
      description: Service configuration
    metric:
      title: metric
      type: object
      properties:
        Metrics:
          title: Metrics
          type: string
        Service:
          title: Service
          type: string
      description: Service metrics
    operation:
      title: operation
      type: object
      properties:
        action:
          title: Action
          type: string
        services:
          uniqueItems: true
          type: array
          items:
            type: string
      description: Service operation
