// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import models "github.com/edgexfoundry/go-mod-core-contracts/models"

// IntervalActionLoader is an autogenerated mock type for the IntervalActionLoader type
type IntervalActionLoader struct {
	mock.Mock
}

// IntervalActionsByIntervalName provides a mock function with given fields: name
func (_m *IntervalActionLoader) IntervalActionsByIntervalName(name string) ([]models.IntervalAction, error) {
	ret := _m.Called(name)

	var r0 []models.IntervalAction
	if rf, ok := ret.Get(0).(func(string) []models.IntervalAction); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.IntervalAction)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
