// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import models "github.com/edgexfoundry/go-mod-core-contracts/models"

// DeviceProfileAdder is an autogenerated mock type for the DeviceProfileAdder type
type DeviceProfileAdder struct {
	mock.Mock
}

// AddDeviceProfile provides a mock function with given fields: d
func (_m *DeviceProfileAdder) AddDeviceProfile(d models.DeviceProfile) (string, error) {
	ret := _m.Called(d)

	var r0 string
	if rf, ok := ret.Get(0).(func(models.DeviceProfile) string); ok {
		r0 = rf(d)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(models.DeviceProfile) error); ok {
		r1 = rf(d)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
