// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"

import mock "github.com/stretchr/testify/mock"
import models "github.com/edgexfoundry/go-mod-core-contracts/models"

// ValueDescriptorAdder is an autogenerated mock type for the ValueDescriptorAdder type
type ValueDescriptorAdder struct {
	mock.Mock
}

// Add provides a mock function with given fields: vdr, ctx
func (_m *ValueDescriptorAdder) Add(ctx context.Context, vdr *models.ValueDescriptor) (string, error) {
	ret := _m.Called(vdr, ctx)

	var r0 string
	if rf, ok := ret.Get(0).(func(*models.ValueDescriptor, context.Context) string); ok {
		r0 = rf(vdr, ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*models.ValueDescriptor, context.Context) error); ok {
		r1 = rf(vdr, ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
