// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import models "github.com/edgexfoundry/go-mod-core-contracts/models"

// CommandByIdExecutor is an autogenerated mock type for the CommandByIdExecutor type
type CommandByIdExecutor struct {
	mock.Mock
}

// Execute provides a mock function with given fields:
func (_m *CommandByIdExecutor) Execute() (models.Command, error) {
	ret := _m.Called()

	var r0 models.Command
	if rf, ok := ret.Get(0).(func() models.Command); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(models.Command)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
