#!/bin/bash

# This hook is triggered after the bind mount is added as a result of a
# connection for edgex-secretstore-token content interface.
#
#
# The connection can happen before or after security-secretstore-setup:
#
#   BEFORE when a consumer snap (from the same publisher) is installed before
#   the edgexfoundry snap and the content interface is auto-connected.
#
#   AFTER, when:
#     1. A consumer snap (from the same publisher) is installed after the
#        edgexfoundry snap and the content interface is auto-connected.
#     2. A connection to an external consumer snap is made manually after the
#        installation of the edgexfoundry snap.
#
# Note: Since v2.1.0, the security-secretstore-setup is started by the configure
# hook instead of automatically after the installation.

$SNAP/bin/security-secretstore-post-setup.sh "connect-plug-edgex-secretstore-token"
