#!/bin/bash

# This script needs to exist, for an unknown reason to avoid the following error:
#
# Run hook prepare-plug-edgex-secretstore-token of snap "edgexfoundry" (run hook
# "prepare-plug-edgex-secretstore-token": 
# /snap/edgexfoundry/3358/snap/command-chain/snapcraft-runner: 6: exec: 
# /snap/edgexfoundry/3358/meta/hooks/prepare-plug-edgex-secretstore-token: not found)